### PR TITLE
Support rv64

### PR DESCRIPTION
**Pull request by TheThirdOne**
I have something that gives some support for rv64 now. Its not finished, but it is a start.

TODO:
  - [x] Support rv64i instructions
  - [x] Support rv64im instructions
  - [x] Support rv64if instructions
  - [x] Support rv64ifd instructions
  - [x] Update system calls
  - [x] GUI shows 64 bit wide registers
  - [x] GUI allows toggling 64 bit mode
  - [x] CLI allows changing to 64 bit mode
  - [x] Assembler allows 64 bit wide constants 
  - [x] Good error messages and support for 6 bit immediates in shift instructions
  - [x] Testing to prove correct semantics

### CODE REVIEW

**Comment by TheThirdOne** [comment]
This is close enough to finished that feedback would be good. If 32 bit behavior has changed or 64 bit semantics are wrong, please let me know. A fair amount of documentation still needs to be made and I don't have rigorous testing setup yet.

You can find a jar [here](https://github.com/TheThirdOne/rars/releases/tag/pr78)

**Comment by fudgenuggets12** [comment]
Thank you so much for this feature!

**Comment by TheThirdOne** [comment]
Currently the thin holding this back is the lack of testing. I have been working on loading ELF files generated by riscv-tests, but that will take a little more effort as ELF loading is a prototype and doesn't support parsing 64 bit ELF files.

**Comment by TheThirdOne** [comment]
A hacky way of loading elf files worked, and RARS now passes binary rv64 tests. I don't have the tests committed yet though. I think I will get the CLI set up quickly and then manually review all of the system calls.

**Pull request merged**
