### PR TITLE
Fix/instruction counter

### PR DESCRIPTION
**Pull request by esperz2019**
Modified InstructionCounter Tool to support B and J-type instruction count.

### CODE REVIEW

**Comment by TheThirdOne** [comment]
Great work. This definitely fixes the first half of #21.

I realized when reviewing this that `BasicInstructionFormat.R4_FORMAT` isn't covered. This means instructions like `fmadd.s` won't be categorized. I should have mentioned this in the original issue.

Would you like to also add support for the R4 format? If not, I'll merge in your changes as is and add it myself.

**Comment by esperz2019** [comment]
Sure. Sorry I haven't read about the F extension till short before, so I skipped it.

**Comment by TheThirdOne** [comment]
Thanks for the quick response.

Just for future reference, you don't need to close a Pull Request and make a new one to update it. You should be able to see ef7286a in the list of commits on this page.

**Comment by esperz2019** [comment]
Oh, I see it.

**Pull request closed without merging**
