### PR TITLE
Fixed text color on tabs in MacOS

### LINKED ISSUE #128: Tabs background and text both white when selected - MacOS
On MacOS, when a tab is selected, the background is white, but the text is also white. 

Here is a screenshot of the issue.
Screen Shot 2021-09-06 at 1 48 00 PM

Very easy fix I am working on, will link PR when complete.

### PR DESCRIPTION
**Pull request by Juicestus**
Changed the value of the text to be surrounded by HTML that changes nothing about the style, but makes the coloring correct. 

Example:
```"Run I/O"``` becomes ```"<html><center><p>Run I/O</p></center></html>"```

Also added checks for .DS_Store files generated by the MacOS file system in the .gitignore.
I also added checks for build and rars.jar, which are produced by the build, but just in you accidentally git add them as I did.

Closes #128

### CODE REVIEW

**Comment by TheThirdOne** [comment]
Do you know why this fixes the  issue? I would rather not make all of the text html if there is a more understandable way to fix this issue.

**Comment by Juicestus** [comment]
I believe it is because HTML defaults the foreground color to black.
I can implement a fix similar to [the one mentioned here](https://bugs.openjdk.java.net/browse/JDK-8257595) tonight.

**Comment by Juicestus** [comment]
I made it use setForeground rather than HTML.

**Comment by TheThirdOne** [comment]
Sorry for taking a while to get this in. I had a few modifications I wanted to make, but didn't have the time to get to it until now.

**Pull request closed without merging**
